## For Regression data set

In [1]:
import numpy as np
import pandas as pd

In [2]:
df = pd.DataFrame([[8,8,4],[7,9,5],[6,10,6],[5,12,7]],columns=['cgpa','profile_score','LPA'])

In [3]:
df

   cgpa  profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [4]:
def initialize_parameters(layer_dims):
    np.random.seed(3)
    parameters = {}
    L = len(layer_dims)

    for i in range(1,L):
        parameters['W'+str(i)] = np.ones((layer_dims[i-1],layer_dims[i]))*0.1
        parameters["B"+str(i)] = np.zeros((layer_dims[i],1))
    
    return parameters

In [5]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [6]:
def linear_forward(A_prev, W,b):
    Z = np.dot(W.T, A_prev) + b 
    return Z



#  to check the inner side 
print(parameters['B2'])
print(parameters['W2'].T)

NameError: name 'parameters' is not defined

In [ ]:
# forward prop
def L_layer_forward(X,parameter):
    A = X 
    L = len(parameter)//2
    for i in range(1,L+1):
        A_prev = A
        #print("A_prev",A_prev)
        
        W = parameter['W'+str(i)]
        b = parameter['B'+str(i)]
        #print(f'Weight{i} is {W}')
        #print(f'bias{i} is {b}')
        


        
        A = linear_forward(A_prev,W,b) 
    return A,A_prev

In [ ]:
X = df[['cgpa','profile_score']].values[0].reshape(2,1)
Y = df['LPA'].values[0]
parameters = initialize_parameters([2,2,1])
len(parameters)
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [ ]:
Y_hat , A1 =L_layer_forward(X,parameters)
Y_hat=Y_hat[0][0]

In [ ]:
A1[0][0]
parameters['W1']

array([[0.1, 0.1],
       [0.1, 0.1]])

In [ ]:
def update_parameters(parameters,Y,Y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * 2*(Y-Y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 * 2*(Y-Y_hat)*A1[1][0])
    parameters['B2'][0][0] = parameters['B2'][0][0] + (0.001 * 2*(Y-Y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * 2*(Y-Y_hat)*parameters["W2"][0][0]*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][0][0]*X[1][0])
    parameters['B1'][0][0] = parameters['B1'][0][0] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][0][0])
      
    parameters['W1'][1][0] = parameters['W1'][1][0] +( 0.001 * 2*(Y-Y_hat)*parameters["W2"][1][0]*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][1][0]*X[1][0])
    parameters['B1'][1][0] = parameters['B1'][1][0] + (0.001 * 2*(Y-Y_hat)*parameters['W2'][1][0])

In [ ]:
update_parameters(parameters,Y,Y_hat,A1,X)

In [ ]:
#X = df[['cgpa','profile_score']].values[3].reshape(2,1)
##Y = df['LPA'].values[3]
#parameters = initialize_parameters([2,2,1])
#len(parameters)
#parameters

In [ ]:
parameters

{'W1': array([[7.6225088, 7.6225088],
        [7.6225088, 7.6225088]]),
 'B1': array([[0.9403136],
        [0.9403136]]),
 'W2': array([[1.2776],
        [1.2776]]),
 'B2': array([[0.736]])}

In [ ]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 10

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df[['cgpa', 'profile_score']].values[j].reshape(2,1) 
    y = df['LPA'].values[j]

    # Parameter initialization


    y_hat,A1 = L_layer_forward(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters(parameters,Y,Y_hat,A1,X)

    Loss.append((y-y_hat)**2)

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  26.609404847272543
Epoch -  2 Loss -  21.971059673284614
Epoch -  3 Loss -  14.320642571350543
Epoch -  4 Loss -  4.071207881588833
Epoch -  5 Loss -  2.285033177056581
Epoch -  6 Loss -  71.88849570698454
Epoch -  7 Loss -  501.6894939512356
Epoch -  8 Loss -  2520.5043101925457
Epoch -  9 Loss -  11188.697339583008
Epoch -  10 Loss -  47029.39726524371

{'W1': array([[1.82082826, 2.76042751],
        [2.33773713, 3.56748471]]),
 'B1': array([[0.26907334],
        [0.35032955]]),
 'W2': array([[3.00901866],
        [4.19923293]]),
 'B2': array([[0.2944]])}

# know using keras

In [ ]:
df

   cgpa  profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7

In [ ]:
import tensorflow
from tensorflow import keras
from keras import Sequential
from keras.layers import Dense

In [ ]:
model = Sequential()
model.add(Dense(2,activation='linear',input_dim=2))
model.add(Dense(1,activation='linear'))

/Users/All file hear/complete ai /Deep learning/.venv/lib/python3.13/site-packages/keras/src/layers/core/dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [ ]:
model.summary()

Model: "sequential_2"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense_2 (Dense)                 │ (None, 2)              │             6 │
├─────────────────────────────────┼────────────────────────┼───────────────┤
│ dense_3 (Dense)                 │ (None, 1)              │             3 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 9 (36.00 B)

 Trainable params: 9 (36.00 B)

 Non-trainable params: 0 (0.00 B)

In [ ]:
model.get_weights()

[array([[0.1, 0.1],
        [0.1, 0.1]], dtype=float32),
 array([0., 0.], dtype=float32),
 array([[0.1],
        [0.1]], dtype=float32),
 array([0.], dtype=float32)]

In [ ]:
new_weight = [
    np.array([[0.1, 0.1],
              [0.1, 0.1]], dtype=np.float32),

    np.array([0, 0], dtype=np.float32),

    np.array([[0.1],
              [0.1]], dtype=np.float32),

    np.array([0], dtype=np.float32)
]

In [ ]:
model.set_weights(new_weight)

In [ ]:
optimizer = keras.optimizers.Adam(learning_rate=0.001)

In [ ]:
model.compile(loss ='mean_squared_error',optimizer=optimizer)

In [ ]:
X = df.drop(columns=['LPA'])
Y = df['LPA']
X.values

array([[ 8,  8],
       [ 7,  9],
       [ 6, 10],
       [ 5, 12]])

In [ ]:
model.fit(X.values,Y.values,epochs=75,batch_size=1,verbose=1)

Epoch 1/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.5585
Epoch 2/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 18.0527
Epoch 3/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 17.4779
Epoch 4/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 16.9821
Epoch 5/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 16.4430
Epoch 6/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.8959
Epoch 7/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 15.3081
Epoch 8/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 14.7825
Epoch 9/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 14.2967
Epoch 10/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.7229
Epoch 11/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 13.2335
Epoch 12/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.6579
Epoch 13/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 12.1662
Epoch 14/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.6444
Epoch 15/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 11.1797
Epoch 16/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.6905
Epoch 17/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 10.1765
Epoch 18/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 9.7177
Epoch 19/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 9.2714
Epoch 20/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 8.8262
Epoch 21/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 8.3735
Epoch 22/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.9413
Epoch 23/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.5296
Epoch 24/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 7.1105
Epoch 25/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.7740
Epoch 26/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 6.3472
Epoch 27/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 6.0621
Epoch 28/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.6527
Epoch 29/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.3253
Epoch 30/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 5.0702
Epoch 31/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 4.7368
Epoch 32/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.4728
Epoch 33/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 4.2287
Epoch 34/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.9187
Epoch 35/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.6928
Epoch 36/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.4895
Epoch 37/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 3.2916
Epoch 38/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 3.0779
Epoch 39/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.9036
Epoch 40/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.7308
Epoch 41/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 2.5662
Epoch 42/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.4469
Epoch 43/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.3023
Epoch 44/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.1876
Epoch 45/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 2.0542
Epoch 46/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.9566
Epoch 47/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.8299
Epoch 48/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.7591
Epoch 49/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6785
Epoch 50/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.6036
Epoch 51/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.5635
Epoch 52/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.4815
Epoch 53/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.4431
Epoch 54/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3944
Epoch 55/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3544
Epoch 56/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.3039
Epoch 57/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2581
Epoch 58/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2313
Epoch 59/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.2238
Epoch 60/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1954
Epoch 61/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1561
Epoch 62/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1585
Epoch 63/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1245
Epoch 64/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1073
Epoch 65/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.1120
Epoch 66/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - loss: 1.0830
Epoch 67/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0870
Epoch 68/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0643
Epoch 69/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0597
Epoch 70/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0533
Epoch 71/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0421
Epoch 72/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0369
Epoch 73/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 4ms/step - loss: 1.0347
Epoch 74/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0374
Epoch 75/75
4/4 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step - loss: 1.0215

In [ ]:
model.get_weights()

[array([[0.37893015, 0.37893015],
        [0.394673  , 0.394673  ]], dtype=float32),
 array([0.28954715, 0.28954715], dtype=float32),
 array([[0.3920001],
        [0.3920001]], dtype=float32),
 array([0.21505721], dtype=float32)]

## For classification

In [137]:
df2 = pd.DataFrame([[8,8,1],[7,9,1],[6,10,0],[5,5,0]],columns=['cgpa','profile_score','LPA'])

In [8]:
initialize_parameters([2,2,1])

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [9]:
def segmoid(Z):
     A = 1/ (1+np.exp(-Z))
     return A

In [10]:
def linear_forward(A_prev, W,b):
    Z = np.dot(W.T, A_prev) + b 
    A = segmoid(Z)
    return Z

In [128]:
# forward prop
def L_layer_forward2(X,parameter):
    A = X 
    L = len(parameter)//2
    for i in range(1,L+1):
        A_prev = A
        W = parameter['W'+str(i)]
        b = parameter['B'+str(i)]        
        A = linear_forward(A_prev,W,b) 
    return A,A_prev

In [20]:
def update_parameters2(parameters,Y,Y_hat,A1,X):
    parameters['W2'][0][0] = parameters['W2'][0][0] + (0.001 * (Y-Y_hat)*A1[0][0])
    parameters['W2'][1][0] = parameters['W2'][1][0] + (0.001 *(Y-Y_hat)*A1[1][0])
    parameters['B2'][0][0] = parameters['B2'][0][0] + (0.001 * (Y-Y_hat))
    
    parameters['W1'][0][0] = parameters['W1'][0][0] + (0.001 * (Y-Y_hat)*parameters["W2"][0][0]*A1[0][0]*(1-A1[0][0])*X[0][0])
    parameters['W1'][0][1] = parameters['W1'][0][1] + (0.001 * (Y-Y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0])*X[1][0])
    parameters['B1'][0][0] = parameters['B1'][0][0] + (0.001 * (Y-Y_hat)*parameters['W2'][0][0]*A1[0][0]*(1-A1[0][0]))
      
    parameters['W1'][1][0] = parameters['W1'][1][0] +( 0.001 * (Y-Y_hat)*parameters["W2"][1][0]*A1[1][0]*(1-A1[1][0])*X[0][0])
    parameters['W1'][1][1] = parameters['W1'][1][1] + (0.001 * (Y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0])*X[1][0])
    parameters['B1'][1][0] = parameters['B1'][1][0] + (0.001 * (Y-Y_hat)*parameters['W2'][1][0]*A1[1][0]*(1-A1[1][0]))

In [139]:
X = df2[['cgpa','profile_score']].values[0].reshape(2,1)
Y = df2['LPA'].values[0]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

In [121]:
update_parameters2(parameters,Y,Y_hat,A1,X)

In [123]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

2.297807649467193

In [103]:
parameters

{'W1': array([[0.1, 0.1],
        [0.1, 0.1]]),
 'B1': array([[0.],
        [0.]]),
 'W2': array([[0.1],
        [0.1]]),
 'B2': array([[0.]])}

In [140]:
X = df2[['cgpa','profile_score']].values[1].reshape(2,1)
Y = df2['LPA'].values[1]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

parameters

{'W1': array([[ 0.08463773, -0.18147328],
        [ 0.04859566,  0.16233027]]),
 'B1': array([[-0.0151757 ],
        [ 0.00258228]]),
 'W2': array([[2.20583104],
        [0.9907864 ]]),
 'B2': array([[2.07990108]])}

In [108]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

3.8928773946702395

In [109]:
update_parameters2(parameters,Y,Y_hat,A1,X)

In [141]:
X = df2[['cgpa','profile_score']].values[2].reshape(2,1)
Y = df2['LPA'].values[2]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

parameters

{'W1': array([[ 0.08463773, -0.18147328],
        [ 0.04859566,  0.16233027]]),
 'B1': array([[-0.0151757 ],
        [ 0.00258228]]),
 'W2': array([[2.20583104],
        [0.9907864 ]]),
 'B2': array([[2.07990108]])}

In [111]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

4.238352147542699

In [112]:
update_parameters2(parameters,Y,Y_hat,A1,X)

In [142]:
X = df2[['cgpa','profile_score']].values[3].reshape(2,1)
Y = df2['LPA'].values[3]
#parameters = initialize_parameters([2,2,1])

Y_hat, A1 = L_layer_forward(X,parameters)
Y_hat = Y_hat[0][0]

parameters

{'W1': array([[ 0.08463773, -0.18147328],
        [ 0.04859566,  0.16233027]]),
 'B1': array([[-0.0151757 ],
        [ 0.00258228]]),
 'W2': array([[2.20583104],
        [0.9907864 ]]),
 'B2': array([[2.07990108]])}

In [ ]:
print(-Y*np.log(Y_hat)-(1-Y)*np.log(1-Y_hat))

3.817965326024675

In [146]:
update_parameters2(parameters,Y,Y_hat,A1,X)
df2

   cgpa  profile_score  LPA
0     8              8    1
1     7              9    1
2     6             10    0
3     5              5    0

In [151]:
# epochs implementation

parameters = initialize_parameters([2,2,1])
epochs = 1000

for i in range(epochs):

  Loss = []

  for j in range(df.shape[0]):

    X = df2[['cgpa', 'profile_score']].values[j].reshape(2,1) 
    y = df2['LPA'].values[j]

    # Parameter initialization


    y_hat,A1 = L_layer_forward2(X,parameters)
    y_hat = y_hat[0][0]

    update_parameters2(parameters,y,y_hat,A1,X)

    Loss.append(-y*np.log(y_hat)-(1-y)*np.log(1-y_hat))

  print('Epoch - ',i+1,'Loss - ',np.array(Loss).mean())

parameters

Epoch -  1 Loss -  0.7226409132810659
Epoch -  2 Loss -  0.7199303929978415
Epoch -  3 Loss -  0.7173685549244734
Epoch -  4 Loss -  0.7149435473207086
Epoch -  5 Loss -  0.7126446578162371
Epoch -  6 Loss -  0.7104621851791708
Epoch -  7 Loss -  0.7083873277039501
Epoch -  8 Loss -  0.706412085786036
Epoch -  9 Loss -  0.7045291766466059
Epoch -  10 Loss -  0.7027319594955093
Epoch -  11 Loss -  0.7010143696887835
Epoch -  12 Loss -  0.6993708606589578
Epoch -  13 Loss -  0.6977963525808267
Epoch -  14 Loss -  0.6962861868892529
Epoch -  15 Loss -  0.6948360858943665
Epoch -  16 Loss -  0.6934421168477197
Epoch -  17 Loss -  0.6921006599041235
Epoch -  18 Loss -  0.6908083795009362
Epoch -  19 Loss -  0.6895621987418944
Epoch -  20 Loss -  0.6883592764280968
Epoch -  21 Loss -  0.6871969864260763
Epoch -  22 Loss -  0.6860728991033477
Epoch -  23 Loss -  0.6849847645964656
Epoch -  24 Loss -  0.6839304977063946
Epoch -  25 Loss -  0.6829081642416136
Epoch -  26 Loss -  0.6819159686514874
Epoch -  27 Loss -  0.6809522428115521
Epoch -  28 Loss -  0.6800154358389272
Epoch -  29 Loss -  0.6791041048304657
Epoch -  30 Loss -  0.6782169064287484
Epoch -  31 Loss -  0.6773525891319654
Epoch -  32 Loss -  0.6765099862732425
Epoch -  33 Loss -  0.6756880096033179
Epoch -  34 Loss -  0.6748856434177851
Epoch -  35 Loss -  0.6741019391765388
Epoch -  36 Loss -  0.6733360105687031
Epoch -  37 Loss -  0.6725870289813064
Epoch -  38 Loss -  0.6718542193343464
Epoch -  39 Loss -  0.6711368562487813
Epoch -  40 Loss -  0.6704342605174091
Epoch -  41 Loss -  0.6697457958516495
Epoch -  42 Loss -  0.669070865879941
Epoch -  43 Loss -  0.6684089113758774
Epoch -  44 Loss -  0.667759407696341
Epoch -  45 Loss -  0.6671218624118008
Epoch -  46 Loss -  0.6664958131126528
Epoch -  47 Loss -  0.6658808253769949
Epoch -  48 Loss -  0.6652764908865971
Epoch -  49 Loss -  0.6646824256790491
Epoch -  50 Loss -  0.6640982685251625
Epoch -  51 Loss -  0.6635236794216922
Epoch -  52 Loss -  0.6629583381903253
Epoch -  53 Loss -  0.6624019431746865
Epoch -  54 Loss -  0.6618542100278271
Epoch -  55 Loss -  0.6613148705833146
Epoch -  56 Loss -  0.6607836718036287
Epoch -  57 Loss -  0.660260374800096
Epoch -  58 Loss -  0.6597447539190842
Epoch -  59 Loss -  0.6592365958896059
Epoch -  60 Loss -  0.6587356990278825
Epoch -  61 Loss -  0.6582418724947743
Epoch -  62 Loss -  0.657754935602316
Epoch -  63 Loss -  0.6572747171658891
Epoch -  64 Loss -  0.6568010548988367
Epoch -  65 Loss -  0.6563337948465736
Epoch -  66 Loss -  0.6558727908574732
Epoch -  67 Loss -  0.6554179040880118
Epoch -  68 Loss -  0.654969002539852
Epoch -  69 Loss -  0.6545259606267076
Epoch -  70 Loss -  0.6540886587690021
Epoch -  71 Loss -  0.6536569830144695
Epoch -  72 Loss -  0.6532308246829857
Epoch -  73 Loss -  0.6528100800340424
Epoch -  74 Loss -  0.652394649955381
Epoch -  75 Loss -  0.6519844396714188
Epoch -  76 Loss -  0.6515793584701851
Epoch -  77 Loss -  0.6511793194475844
Epoch -  78 Loss -  0.6507842392678737
Epoch -  79 Loss -  0.6503940379393253
Epoch -  80 Loss -  0.6500086386041151
Epoch -  81 Loss -  0.6496279673415347
Epoch -  82 Loss -  0.6492519529836929
Epoch -  83 Loss -  0.6488805269429238
Epoch -  84 Loss -  0.6485136230501696
Epoch -  85 Loss -  0.6481511774036568
Epoch -  86 Loss -  0.6477931282272245
Epoch -  87 Loss -  0.6474394157377086
Epoch -  88 Loss -  0.6470899820208214
Epoch -  89 Loss -  0.6467447709150026
Epoch -  90 Loss -  0.6464037279027508
Epoch -  91 Loss -  0.6460668000089752
Epoch -  92 Loss -  0.6457339357059358
Epoch -  93 Loss -  0.645405084824367
Epoch -  94 Loss -  0.6450801984704072
Epoch -  95 Loss -  0.6447592289479744
Epoch -  96 Loss -  0.6444421296862566
Epoch -  97 Loss -  0.6441288551720015
Epoch -  98 Loss -  0.6438193608863101
Epoch -  99 Loss -  0.6435136032456585
Epoch -  100 Loss -  0.643211539546886
Epoch -  101 Loss -  0.6429131279159066
Epoch -  102 Loss -  0.6426183272599105
Epoch -  103 Loss -  0.6423270972228439
Epoch -  104 Loss -  0.6420393981439596
Epoch -  105 Loss -  0.6417551910192496
Epoch -  106 Loss -  0.6414744374655783
Epoch -  107 Loss -  0.6411970996873484
Epoch -  108 Loss -  0.6409231404455387
Epoch -  109 Loss -  0.640652523028965
Epoch -  110 Loss -  0.6403852112276244
Epoch -  111 Loss -  0.6401211693079856
Epoch -  112 Loss -  0.6398603619901064
Epoch -  113 Loss -  0.6396027544264578
Epoch -  114 Loss -  0.6393483121823436
Epoch -  115 Loss -  0.639097001217812
Epoch -  116 Loss -  0.6388487878709643
Epoch -  117 Loss -  0.6386036388425628
Epoch -  118 Loss -  0.6383615211818574
Epoch -  119 Loss -  0.6381224022735443
Epoch -  120 Loss -  0.6378862498257838
Epoch -  121 Loss -  0.6376530318592035
Epoch -  122 Loss -  0.6374227166968185
Epoch -  123 Loss -  0.6371952729548069
Epoch -  124 Loss -  0.6369706695340784
Epoch -  125 Loss -  0.6367488756125801
Epoch -  126 Loss -  0.6365298606382894
Epoch -  127 Loss -  0.6363135943228395
Epoch -  128 Loss -  0.6361000466357352
Epoch -  129 Loss -  0.6358891877991111
Epoch -  130 Loss -  0.6356809882829957
Epoch -  131 Loss -  0.6354754188010385
Epoch -  132 Loss -  0.6352724503066649
Epoch -  133 Loss -  0.6350720539896284
Epoch -  134 Loss -  0.634874201272922
Epoch -  135 Loss -  0.6346788638100249
Epoch -  136 Loss -  0.6344860134824525
Epoch -  137 Loss -  0.6342956223975859
Epoch -  138 Loss -  0.6341076628867545
Epoch -  139 Loss -  0.6339221075035515
Epoch -  140 Loss -  0.6337389290223571
Epoch -  141 Loss -  0.6335581004370529
Epoch -  142 Loss -  0.6333795949599075
Epoch -  143 Loss -  0.6332033860206153
Epoch -  144 Loss -  0.6330294472654733
Epoch -  145 Loss -  0.6328577525566794
Epoch -  146 Loss -  0.6326882759717406
Epoch -  147 Loss -  0.6325209918029747
Epoch -  148 Loss -  0.632355874557098
Epoch -  149 Loss -  0.632192898954881
Epoch -  150 Loss -  0.6320320399308688
Epoch -  151 Loss -  0.6318732726331526
Epoch -  152 Loss -  0.6317165724231835
Epoch -  153 Loss -  0.6315619148756206
Epoch -  154 Loss -  0.6314092757782082
Epoch -  155 Loss -  0.6312586311316702
Epoch -  156 Loss -  0.6311099571496221
Epoch -  157 Loss -  0.6309632302584862
Epoch -  158 Loss -  0.6308184270974133
Epoch -  159 Loss -  0.6306755245181993
Epoch -  160 Loss -  0.6305344995851969
Epoch -  161 Loss -  0.6303953295752138
Epoch -  162 Loss -  0.6302579919774001
Epoch -  163 Loss -  0.6301224644931133
Epoch -  164 Loss -  0.629988725035766
Epoch -  165 Loss -  0.6298567517306489
Epoch -  166 Loss -  0.6297265229147272
Epoch -  167 Loss -  0.6295980171364103
Epoch -  168 Loss -  0.6294712131552912
Epoch -  169 Loss -  0.6293460899418551
Epoch -  170 Loss -  0.6292226266771542
Epoch -  171 Loss -  0.6291008027524513
Epoch -  172 Loss -  0.6289805977688251
Epoch -  173 Loss -  0.6288619915367437
Epoch -  174 Loss -  0.6287449640756001
Epoch -  175 Loss -  0.6286294956132111
Epoch -  176 Loss -  0.6285155665852807
Epoch -  177 Loss -  0.6284031576348258
Epoch -  178 Loss -  0.6282922496115649
Epoch -  179 Loss -  0.6281828235712705
Epoch -  180 Loss -  0.628074860775084
Epoch -  181 Loss -  0.6279683426887952
Epoch -  182 Loss -  0.6278632509820848
Epoch -  183 Loss -  0.627759567527732
Epoch -  184 Loss -  0.6276572744007861
Epoch -  185 Loss -  0.6275563538777049
Epoch -  186 Loss -  0.6274567884354573
Epoch -  187 Loss -  0.6273585607505946
Epoch -  188 Loss -  0.6272616536982879
Epoch -  189 Loss -  0.6271660503513341
Epoch -  190 Loss -  0.627071733979131
Epoch -  191 Loss -  0.6269786880466225
Epoch -  192 Loss -  0.6268868962132141
Epoch -  193 Loss -  0.6267963423316602
Epoch -  194 Loss -  0.6267070104469235
Epoch -  195 Loss -  0.6266188847950087
Epoch -  196 Loss -  0.6265319498017704
Epoch -  197 Loss -  0.6264461900816943
Epoch -  198 Loss -  0.6263615904366587
Epoch -  199 Loss -  0.626278135854669
Epoch -  200 Loss -  0.626195811508573
Epoch -  201 Loss -  0.6261146027547543
Epoch -  202 Loss -  0.6260344951318063
Epoch -  203 Loss -  0.6259554743591873
Epoch -  204 Loss -  0.6258775263358561
Epoch -  205 Loss -  0.6258006371388931
Epoch -  206 Loss -  0.6257247930221034
Epoch -  207 Loss -  0.6256499804146054
Epoch -  208 Loss -  0.6255761859194046
Epoch -  209 Loss -  0.6255033963119553
Epoch -  210 Loss -  0.6254315985387078
Epoch -  211 Loss -  0.6253607797156462
Epoch -  212 Loss -  0.6252909271268141
Epoch -  213 Loss -  0.6252220282228304
Epoch -  214 Loss -  0.625154070619397
Epoch -  215 Loss -  0.6250870420957974
Epoch -  216 Loss -  0.6250209305933879
Epoch -  217 Loss -  0.6249557242140834
Epoch -  218 Loss -  0.6248914112188354
Epoch -  219 Loss -  0.6248279800261062
Epoch -  220 Loss -  0.6247654192103376
Epoch -  221 Loss -  0.6247037175004186
Epoch -  222 Loss -  0.6246428637781462
Epoch -  223 Loss -  0.624582847076687
Epoch -  224 Loss -  0.6245236565790352
Epoch -  225 Loss -  0.6244652816164716
Epoch -  226 Loss -  0.6244077116670197
Epoch -  227 Loss -  0.6243509363539045
Epoch -  228 Loss -  0.6242949454440099
Epoch -  229 Loss -  0.6242397288463395
Epoch -  230 Loss -  0.6241852766104776
Epoch -  231 Loss -  0.6241315789250539
Epoch -  232 Loss -  0.6240786261162099
Epoch -  233 Loss -  0.6240264086460702
Epoch -  234 Loss -  0.6239749171112168
Epoch -  235 Loss -  0.6239241422411673
Epoch -  236 Loss -  0.6238740748968601
Epoch -  237 Loss -  0.6238247060691416
Epoch -  238 Loss -  0.6237760268772623
Epoch -  239 Loss -  0.6237280285673762
Epoch -  240 Loss -  0.6236807025110491
Epoch -  241 Loss -  0.6236340402037716
Epoch -  242 Loss -  0.6235880332634807
Epoch -  243 Loss -  0.623542673429088
Epoch -  244 Loss -  0.6234979525590163
Epoch -  245 Loss -  0.6234538626297434
Epoch -  246 Loss -  0.6234103957343559
Epoch -  247 Loss -  0.6233675440811095
Epoch -  248 Loss -  0.623325299992
Epoch -  249 Loss -  0.6232836559013433
Epoch -  250 Loss -  0.6232426043543624
Epoch -  251 Loss -  0.6232021380057885
Epoch -  252 Loss -  0.6231622496184672
Epoch -  253 Loss -  0.6231229320619777
Epoch -  254 Loss -  0.6230841783112618
Epoch -  255 Loss -  0.6230459814452619
Epoch -  256 Loss -  0.623008334645571
Epoch -  257 Loss -  0.6229712311950935
Epoch -  258 Loss -  0.6229346644767146
Epoch -  259 Loss -  0.6228986279719837
Epoch -  260 Loss -  0.6228631152598075
Epoch -  261 Loss -  0.6228281200151531
Epoch -  262 Loss -  0.6227936360077649
Epoch -  263 Loss -  0.6227596571008908
Epoch -  264 Loss -  0.6227261772500212
Epoch -  265 Loss -  0.6226931905016386
Epoch -  266 Loss -  0.6226606909919797
Epoch -  267 Loss -  0.6226286729458087
Epoch -  268 Loss -  0.6225971306752025
Epoch -  269 Loss -  0.622566058578347
Epoch -  270 Loss -  0.6225354511383472
Epoch -  271 Loss -  0.6225053029220463
Epoch -  272 Loss -  0.6224756085788601
Epoch -  273 Loss -  0.6224463628396195
Epoch -  274 Loss -  0.6224175605154278
Epoch -  275 Loss -  0.6223891964965296
Epoch -  276 Loss -  0.6223612657511901
Epoch -  277 Loss -  0.6223337633245882
Epoch -  278 Loss -  0.6223066843377193
Epoch -  279 Loss -  0.622280023986313
Epoch -  280 Loss -  0.6222537775397596
Epoch -  281 Loss -  0.6222279403400508
Epoch -  282 Loss -  0.6222025078007307
Epoch -  283 Loss -  0.6221774754058603
Epoch -  284 Loss -  0.6221528387089909
Epoch -  285 Loss -  0.6221285933321532
Epoch -  286 Loss -  0.6221047349648539
Epoch -  287 Loss -  0.622081259363088
Epoch -  288 Loss -  0.6220581623483585
Epoch -  289 Loss -  0.622035439806712
Epoch -  290 Loss -  0.6220130876877821
Epoch -  291 Loss -  0.6219911020038457
Epoch -  292 Loss -  0.6219694788288921
Epoch -  293 Loss -  0.6219482142977
Epoch -  294 Loss -  0.6219273046049294
Epoch -  295 Loss -  0.6219067460042219
Epoch -  296 Loss -  0.6218865348073136
Epoch -  297 Loss -  0.6218666673831581
Epoch -  298 Loss -  0.6218471401570617
Epoch -  299 Loss -  0.6218279496098273
Epoch -  300 Loss -  0.6218090922769123
Epoch -  301 Loss -  0.6217905647475935
Epoch -  302 Loss -  0.621772363664145
Epoch -  303 Loss -  0.6217544857210264
Epoch -  304 Loss -  0.6217369276640811
Epoch -  305 Loss -  0.6217196862897442
Epoch -  306 Loss -  0.621702758444262
Epoch -  307 Loss -  0.6216861410229211
Epoch -  308 Loss -  0.6216698309692874
Epoch -  309 Loss -  0.6216538252744549
Epoch -  310 Loss -  0.6216381209763058
Epoch -  311 Loss -  0.6216227151587779
Epoch -  312 Loss -  0.621607604951145
Epoch -  313 Loss -  0.6215927875273032
Epoch -  314 Loss -  0.6215782601050703
Epoch -  315 Loss -  0.6215640199454924
Epoch -  316 Loss -  0.6215500643521593
Epoch -  317 Loss -  0.621536390670533
Epoch -  318 Loss -  0.6215229962872798
Epoch -  319 Loss -  0.6215098786296156
Epoch -  320 Loss -  0.6214970351646596
Epoch -  321 Loss -  0.6214844633987948
Epoch -  322 Loss -  0.6214721608770392
Epoch -  323 Loss -  0.6214601251824249
Epoch -  324 Loss -  0.6214483539353866
Epoch -  325 Loss -  0.6214368447931573
Epoch -  326 Loss -  0.6214255954491731
Epoch -  327 Loss -  0.6214146036324867
Epoch -  328 Loss -  0.6214038671071879
Epoch -  329 Loss -  0.621393383671834
Epoch -  330 Loss -  0.6213831511588862
Epoch -  331 Loss -  0.6213731674341553
Epoch -  332 Loss -  0.6213634303962551
Epoch -  333 Loss -  0.6213539379760626
Epoch -  334 Loss -  0.6213446881361876
Epoch -  335 Loss -  0.6213356788704466
Epoch -  336 Loss -  0.621326908203349
Epoch -  337 Loss -  0.6213183741895861
Epoch -  338 Loss -  0.6213100749135301
Epoch -  339 Loss -  0.6213020084887387
Epoch -  340 Loss -  0.6212941730574684
Epoch -  341 Loss -  0.6212865667901936
Epoch -  342 Loss -  0.6212791878851323
Epoch -  343 Loss -  0.6212720345677799
Epoch -  344 Loss -  0.62126510509045
Epoch -  345 Loss -  0.6212583977318188
Epoch -  346 Loss -  0.6212519107964805
Epoch -  347 Loss -  0.6212456426145054
Epoch -  348 Loss -  0.6212395915410069
Epoch -  349 Loss -  0.6212337559557132
Epoch -  350 Loss -  0.6212281342625465
Epoch -  351 Loss -  0.6212227248892073
Epoch -  352 Loss -  0.6212175262867654
Epoch -  353 Loss -  0.621212536929257
Epoch -  354 Loss -  0.6212077553132869
Epoch -  355 Loss -  0.6212031799576382
Epoch -  356 Loss -  0.6211988094028849
Epoch -  357 Loss -  0.6211946422110133
Epoch -  358 Loss -  0.6211906769650472
Epoch -  359 Loss -  0.6211869122686793
Epoch -  360 Loss -  0.6211833467459072
Epoch -  361 Loss -  0.6211799790406762
Epoch -  362 Loss -  0.6211768078165256
Epoch -  363 Loss -  0.6211738317562424
Epoch -  364 Loss -  0.6211710495615177
Epoch -  365 Loss -  0.6211684599526107
Epoch -  366 Loss -  0.6211660616680155
Epoch -  367 Loss -  0.6211638534641344
Epoch -  368 Loss -  0.6211618341149553
Epoch -  369 Loss -  0.6211600024117342
Epoch -  370 Loss -  0.6211583571626822
Epoch -  371 Loss -  0.6211568971926572
Epoch -  372 Loss -  0.6211556213428613
Epoch -  373 Loss -  0.6211545284705403
Epoch -  374 Loss -  0.6211536174486905
Epoch -  375 Loss -  0.6211528871657677
Epoch -  376 Loss -  0.6211523365254019
Epoch -  377 Loss -  0.6211519644461158
Epoch -  378 Loss -  0.6211517698610471
Epoch -  379 Loss -  0.6211517517176766
Epoch -  380 Loss -  0.6211519089775577
Epoch -  381 Loss -  0.6211522406160525
Epoch -  382 Loss -  0.6211527456220713
Epoch -  383 Loss -  0.621153422997814
Epoch -  384 Loss -  0.6211542717585188
Epoch -  385 Loss -  0.6211552909322119
Epoch -  386 Loss -  0.6211564795594623
Epoch -  387 Loss -  0.6211578366931402
Epoch -  388 Loss -  0.6211593613981785
Epoch -  389 Loss -  0.6211610527513385
Epoch -  390 Loss -  0.6211629098409793
Epoch -  391 Loss -  0.6211649317668295
Epoch -  392 Loss -  0.6211671176397641
Epoch -  393 Loss -  0.6211694665815835
Epoch -  394 Loss -  0.6211719777247959
Epoch -  395 Loss -  0.6211746502124044
Epoch -  396 Loss -  0.6211774831976952
Epoch -  397 Loss -  0.6211804758440307
Epoch -  398 Loss -  0.6211836273246452
Epoch -  399 Loss -  0.6211869368224433
Epoch -  400 Loss -  0.6211904035298027
Epoch -  401 Loss -  0.6211940266483779
Epoch -  402 Loss -  0.6211978053889087
Epoch -  403 Loss -  0.6212017389710311
Epoch -  404 Loss -  0.621205826623091
Epoch -  405 Loss -  0.6212100675819603
Epoch -  406 Loss -  0.6212144610928567
Epoch -  407 Loss -  0.6212190064091656
Epoch -  408 Loss -  0.6212237027922652
Epoch -  409 Loss -  0.6212285495113541
Epoch -  410 Loss -  0.6212335458432805
Epoch -  411 Loss -  0.6212386910723763
Epoch -  412 Loss -  0.621243984490292
Epoch -  413 Loss -  0.6212494253958338
Epoch -  414 Loss -  0.6212550130948055
Epoch -  415 Loss -  0.6212607468998501
Epoch -  416 Loss -  0.6212666261302953
Epoch -  417 Loss -  0.6212726501120014
Epoch -  418 Loss -  0.6212788181772111
Epoch -  419 Loss -  0.6212851296644023
Epoch -  420 Loss -  0.621291583918141
Epoch -  421 Loss -  0.6212981802889408
Epoch -  422 Loss -  0.6213049181331196
Epoch -  423 Loss -  0.6213117968126618
Epoch -  424 Loss -  0.6213188156950816
Epoch -  425 Loss -  0.6213259741532884
Epoch -  426 Loss -  0.6213332715654543
Epoch -  427 Loss -  0.6213407073148839
Epoch -  428 Loss -  0.6213482807898856
Epoch -  429 Loss -  0.6213559913836451
Epoch -  430 Loss -  0.621363838494102
Epoch -  431 Loss -  0.6213718215238264
Epoch -  432 Loss -  0.6213799398798983
Epoch -  433 Loss -  0.6213881929737891
Epoch -  434 Loss -  0.6213965802212449
Epoch -  435 Loss -  0.6214051010421716
Epoch -  436 Loss -  0.621413754860521
Epoch -  437 Loss -  0.6214225411041798
Epoch -  438 Loss -  0.6214314592048603
Epoch -  439 Loss -  0.6214405085979916
Epoch -  440 Loss -  0.6214496887226133
Epoch -  441 Loss -  0.621458999021272
Epoch -  442 Loss -  0.6214684389399167
Epoch -  443 Loss -  0.6214780079277984
Epoch -  444 Loss -  0.6214877054373704
Epoch -  445 Loss -  0.6214975309241896
Epoch -  446 Loss -  0.6215074838468196
Epoch -  447 Loss -  0.6215175636667368
Epoch -  448 Loss -  0.6215277698482351
Epoch -  449 Loss -  0.6215381018583349
Epoch -  450 Loss -  0.6215485591666923
Epoch -  451 Loss -  0.6215591412455089
Epoch -  452 Loss -  0.6215698475694454
Epoch -  453 Loss -  0.6215806776155338
Epoch -  454 Loss -  0.6215916308630932
Epoch -  455 Loss -  0.6216027067936458
Epoch -  456 Loss -  0.6216139048908342
Epoch -  457 Loss -  0.6216252246403409
Epoch -  458 Loss -  0.621636665529808
Epoch -  459 Loss -  0.6216482270487593
Epoch -  460 Loss -  0.6216599086885229
Epoch -  461 Loss -  0.6216717099421543
Epoch -  462 Loss -  0.6216836303043626
Epoch -  463 Loss -  0.6216956692714372
Epoch -  464 Loss -  0.6217078263411748
Epoch -  465 Loss -  0.6217201010128081
Epoch -  466 Loss -  0.6217324927869361
Epoch -  467 Loss -  0.6217450011654552
Epoch -  468 Loss -  0.6217576256514913
Epoch -  469 Loss -  0.6217703657493333
Epoch -  470 Loss -  0.6217832209643671
Epoch -  471 Loss -  0.6217961908030116
Epoch -  472 Loss -  0.6218092747726552
Epoch -  473 Loss -  0.6218224723815927
Epoch -  474 Loss -  0.6218357831389651
Epoch -  475 Loss -  0.6218492065546982
Epoch -  476 Loss -  0.6218627421394438
Epoch -  477 Loss -  0.6218763894045215
Epoch -  478 Loss -  0.6218901478618601
Epoch -  479 Loss -  0.6219040170239433
Epoch -  480 Loss -  0.6219179964037522
Epoch -  481 Loss -  0.6219320855147118
Epoch -  482 Loss -  0.6219462838706367
Epoch -  483 Loss -  0.6219605909856797
Epoch -  484 Loss -  0.6219750063742784
Epoch -  485 Loss -  0.6219895295511051
Epoch -  486 Loss -  0.6220041600310162
Epoch -  487 Loss -  0.6220188973290043
Epoch -  488 Loss -  0.6220337409601477
Epoch -  489 Loss -  0.6220486904395648
Epoch -  490 Loss -  0.6220637452823664
Epoch -  491 Loss -  0.6220789050036101
Epoch -  492 Loss -  0.622094169118255
Epoch -  493 Loss -  0.6221095371411176
Epoch -  494 Loss -  0.6221250085868282
Epoch -  495 Loss -  0.6221405829697884
Epoch -  496 Loss -  0.6221562598041284
Epoch -  497 Loss -  0.6221720386036664
Epoch -  498 Loss -  0.622187918881868
Epoch -  499 Loss -  0.6222039001518066
Epoch -  500 Loss -  0.622219981926123
Epoch -  501 Loss -  0.6222361637169894
Epoch -  502 Loss -  0.6222524450360698
Epoch -  503 Loss -  0.6222688253944835
Epoch -  504 Loss -  0.6222853043027694

{'W1': array([[0.0314416 , 0.03906634],
        [0.0979621 , 0.04522464]]),
 'B1': array([[-0.01626734],
        [-0.01173218]]),
 'W2': array([[0.29220758],
        [0.29007451]]),
 'B2': array([[0.06357894]])}

In [136]:
df

   cgpa  profile_score  LPA
0     8              8    4
1     7              9    5
2     6             10    6
3     5             12    7